from .uiconnection import ConnectionKeywords
from .login import LoginKeywords
from .mapping import MappingKeywords
from .navigation import NavigationKeywords
from .performance import PerformanceKeywords
from .profiles import ProfileKeywords
from .screenshot import ScreenshotKeywords
from .sitemanagement import SiteKeywords
from .structure import StructureKeywords
from .systeminfo import SystemInformationKeywords
from .usermanagement import UserKeywords
from .visualanalysis import VisualAnalysisKeywords
from .zones import ZoneKeywords
