mapping = {
    'username':                                 {'id': 'autoUsername'},
    'password':                                 {'id': 'autoPassword'},
    'password verify':                          {'id': 'autoPasswordVerify'},
    'remember user':                            {'id': 'autoRememberUser'},
    'rescan ecu':                               {'id': 'autoRescan'},
    'ip address':                               {'id': 'PART_EditableTextBox'},
    'login':                                    {'id': 'autoLogin'},
    'load local':                               {'id': 'autoLoadLocal'},
    'local site load':                          {'id': 'autoSiteOK'},
    'login error':                              {'id': 'autoLoginError'},
    'import local site':                        {'id': 'autoImportLocalSite'},
    'open system':                              {'id': 'autoOpenSystem'},
    'delete system':                            {'id': 'autoDeleteSystem'},
    'create new site':                          {'id': 'autoNavCREATE A NEW SYSTEM'},
    'open local site':                          {'id': 'autoNavOPEN A SYSTEM'},
    'connect to a site':                        {'id': 'autoNavCONNECT TO A SYSTEM'},
    'progress bar':                             {'id': 'ProgressBar'},

    'inner menu':                               {'id': 'InnerMenu'},
    'home':                                     {'id': 'autoHeaderHome'},
    'undo':                                     {'id': 'autoHeaderUndo'},
    'redo':                                     {'id': 'autoHeaderRedo'},
    'select content':                           {'id': 'autoHeaderSelect'},
    'pan content':                              {'id': 'autoHeaderPan'},
    'zoom content':                             {'id': 'autoHeaderZoom'},
    'edit content':                             {'id': 'autoHeaderEdit'},
    'popup content':                            {'id': 'autoHeaderPopup'},
    'fullscreen content':                       {'id': 'autoHeaderFullscreen'},
    'navigate home':                            {'id': 'autoNavigateHome'},
    'navigate rotate':                          {'id': 'autoNavigateRotate'},
    'navigate pan':                             {'id': 'autoNavigatePan'},
    'navigate tilt':                            {'id': 'autoNavigateTilt'},
    'navigate zoom':                            {'id': 'autoNavigateZoom'},
    'navigate 2d':                              {'id': 'autoNavigate2D'},
    'navigate 3d':                              {'id': 'autoNavigate3D'},
    'navigate search':                          {'id': 'autoNavigateSearch'},
    'main ui window':                           {'id': 'autoControlAreas'},
    'delete item':                              {'id': 'autoItemDelete'},

    'properties menu':                          {'id': 'autoMenuProperties'},
    'mapping menu':                             {'id': 'autoMenuMapping'},

    'profiles menu':                            {'id': 'autoMenuProfiles'},
    'control property networking tool':         {'id': 'autoManagerPropertyNetworkingTool'},
    'control property name':                    {'id': 'autoManagerAreaName'},
    'control property name edit':               {'id': 'autoManagerAreaNameEdit'},
    'control property delete':                  {'id': 'autoManagerPropertyDelete'},
    'profile property name':                    {'id': 'autoProfilePropertyName'},
    'profile property name edit':               {'id': 'autoProfilePropertyNameEdit'},
#    'profile property delete':                  {'id': 'autoProfilePropertyDelete'},
    'profile property delete':                  {'id': 'DeleteProfile'},

    'eula accept':                              {'id': 'autoEulaAccept'},

    'wizard cancel':                            {'id': 'autoCancelButton'},
    'wizard back':                              {'id': 'autoBackButton'},
    'wizard next':                              {'id': 'autoNextButton'},
    'wizard close':                             {'id': 'autoCloseButton'},
    'wizard ok':                                {'id': 'autoOKButton'},
    'wizard finish':                            {'id': 'autoFinishButton'},

    'burger menu':                              {'id': 'autoBurgerMenu'},
    'activate system':                          {'id': 'autoActivateSystem'},
    'popup message':                            {'id': 'autoWindowMessage'},

    'cancel':                                   {'id': 'Cancel'},
    'cancel button':                            {'id': 'CancelButton'},
    'ok button':                                {'id': 'OKButton'},
    'close button':                             {'id': 'CloseButton'},
    'yes button':                               {'id': 'YesButton'},
    'no button':                                {'id': 'NoButton'},
    'start button':                             {'id': 'StartButton'},
    'max button':                               {'id': 'PART_ButtonMaximize'},

    'search bar':                               {'id': 'SearchText'},
    'search results':                           {'id': 'SearchResults'},
    'site explorer tab':                        {'id': 'autoTabSiteExplorer'},
    'site explorer select site':                {'id': 'autoSiteExplorerSelectSite'},
    'site explorer floor':                      {'id': 'Floor '},
    'site tree':                                {'id': 'tvMain'},

    'create control area':                      {'id': 'autoCreateControlArea'},
    #'control area name':                        {'id': 'autoManager{0}'},
    #'control area edit name':                   {'id': 'autoManagerAreaNameEdit'},
    'control area':                             {'id': 'autoControlArea{0}'},
    'control areas':                            {'id': 'autoControlAreas'},
    'control area button':                      {'id': 'autoControlArea'},
    'control area status':                      {'id': 'autoManagerAreaUnmapped'},
    'control area class name':                  {'id': 'ControlArea'},
    'control profile':                          {'id': 'autoControlProfile{0}'},
    'control profile name':                     {'id': 'autoProfileName'},
    'control profile edit name':                {'id': 'autoProfileEditName'},
    'control profile template':                 {'id': 'autoControlProfileTemplate{0}'},
    'control profile list':                     {'id': 'autoProfileTemplatesList'},
    'profile class name':                       {'id': 'Profile_ListItemControl'},
    'profile zone':                             {'id': 'autoZone{0}'},
    'profile scene':                            {'id': 'autoProfile{0}'},
    'profile scene name':                       {'id': 'autoSceneName'},
    'profile scene config':                     {'id': 'autoSceneConfig{0}'},
    'profile scene slider':                     {'id': 'autoSlider'},
    'profile scene slider value':               {'id': 'autoSliderTextBox'},
    'profile personal control':                 {'id': 'autoProfilePersonalControl'},
    'profile access key':                       {'id': 'autoPCAccessKey'},

    'zone name':                                {'id': 'autoZoneName'},
    'zone comfort brightness':                  {'id': 'autoZoneComfortBrightness'},
    'zone occupancy':                           {'id': 'autoZoneOccupancy'},
    'zone time':                                {'id': 'autoMinutesEditBox'},
    'zone slider value':                        {'id': 'autoSliderTextBox'},
    'zone daylight harvesting':                 {'id': 'autoZoneDLHV'},
    'zone dimming':                             {'id': 'autoZoneDimming'},
    'zone dimming time template':               {'id': 'auto{0}Duration'},
    'zone dimming brightness template':         {'id': 'auto{0}Brightness'},
    'zone mapped':                              {'id': 'autoZoneMapped'},
    'zone sequence type':                       {'id': 'autoSequenceTypeComboBox'},
    'zone dlhv type':                           {'id': 'autoDLHVType'},
    'zone dlhv strength':                       {'id': 'autoDLHVStrength'},
    'zone dlhv remainder':                      {'id': 'autoDLHVRemainder'},
    'zone dlhv type setting':                   {'id': 'autoDLHVSelectType'},
    'zone dlhv min brightness':                 {'id': 'autoDLHVMinBrightness'},

    'refresh sites':                            {'id': 'autoRefreshSites'},
    'site list':                                {'id': 'autoSiteList'},
    'site ip address':                          {'id': 'autoSiteIpAddress'},
    'site add manager':                         {'id': 'autoSiteAddManager'},
    'site upgrade':                             {'id': 'autoSiteUpgrade'},
    'site change ip':                           {'id': 'autoSiteChangeIp'},
    'site restart':                             {'id': 'autoSiteRestart'},
    'site identify':                            {'id': 'autoSiteIdentify'},
    'site activate':                            {'id': 'autoSiteActivate'},
    'bring to system':                          {'id': 'autoSiteBringToSite'},
    'site name':                                {'id': 'autoSiteName{0}'},
    'site ip':                                  {'id': 'autoSiteIp{0}'},
    'site firmware':                            {'id': 'autoSiteFirmware{0}-{1}'},
    'site remove':                              {'id': 'autoSiteRemove{0}'},
    'site status':                              {'id': 'autoSiteStatus{0}-{1}'},
    'site comtype':                             {'id': 'autoSiteCom{0}-{1}'},
    'site offset':                              {'id': 'autoSiteOffset{0}-{1}'},

    'system name':                              {'id': 'autoSystemName'},
    'system longitude':                         {'id': 'autoSystemLongitude'},
    'system latitude':                          {'id': 'autoSystemLatitude'},
    'system time zone':                         {'id': 'autoSystemTimeZone'},
    'system address':                           {'id': 'autoSystemAddress'},
    'system contact':                           {'id': 'autoSystemContact'},
    'system additional info':                   {'id': 'autoSystemAdditionalInfo'},

    'add user':                                 {'id': 'autoAddUser'},
    'remove user':                              {'id': 'autoUserRemove{0}'},
    'edit user':                                {'id': 'autoUserEdit{0}'},
    'user fullname':                            {'id': 'autoUserEditFullname'},
    'user username':                            {'id': 'autoUserEditUsername'},
    'user change password':                     {'id': 'autoUserEditChangePassword'},
    'user new password':                        {'id': 'autoUserEditNewPassword'},
    'user confirm password':                    {'id': 'autoUserEditConfirmPassword'},
    'user email':                               {'id': 'autoUserEditEmail'},
    'user group':                               {'id': 'autoUserEditGroup'},
    'user notify emergency':                    {'id': 'autoUserEditNotifyEmerg'},
    'user alarm notification':                  {'id': 'autoUserEditAlarmNotification'},
    'user rights':                              {'id': 'autoUserEditRights'},
    'user rights list':                         {'id': 'autoUserRights'},
    'user right':                               {'id': 'TextBlock'},

    'offline create':                           {'id': 'autoOfflineSiteCreate'},
    'offline import':                           {'id': 'autoOfflineSiteImport'},
    'offline sites':                            {'id': 'autoOfflineSites'},
    'offline site':                             {'id': 'autoOfflineSite{0}'},
    'offline config':                           {'id': 'autoOfflineSiteConfig{0}'},
    'offline export':                           {'id': 'autoOfflineSiteExport{0}'},
    'offline delete':                           {'id': 'autoOfflineSiteDelete{0}'},

    'new site name':                            {'id': 'autoNewSiteName'},
    'new site password':                        {'id': 'autoPassword'},
    'new site customer':                        {'id': 'autoNewSiteCustomer'},
    'new site project':                         {'id': 'autoNewSiteProject'},
    'new site author':                          {'id': 'autoNewSiteAuthor'},
    'new site create':                          {'id': 'autoNewSiteCreate'},

    'backup default snapshot':                  {'id': 'autoDefaultSnapshot'},
    'backup custom snapshot':                   {'id': 'autoCustomSnapshot'},
    'backup polaris logs':                      {'id': 'autoSnapshotPolarisLogs'},
    'backup config data':                       {'id': 'autoSnapshotConfig'},
    'backup ecu data':                          {'id': 'autoSnapshotECUData'},
    'backup start':                             {'id': 'autoSnapshotStart'},
    'backup close':                             {'id': 'autoSnapshotCancel'},
    'backup file':                              {'id': 'autoBackupFile'},
    'backup folder':                            {'id': 'autoBackupFolder'},
    'restore backup file':                      {'id': 'autoRestoreBackupFile'},
    'restore backup status':                    {'id': 'autoRestoreBackupStatus'},
    'restore wink':                             {'id': 'autoWinkECU'},
    'restore rescan':                           {'id': 'autoRescan'},
    'restore target ecu':                       {'id': 'autoRestoreTargetECU'},
    'restore backup source':                    {'id': 'autoRestoreBackupSource'},
    'restore ecu checkbox':                     {'id': 'autoRestoreECUCheckbox{0}'},
    'restore backup ecu':                       {'id': 'autoRestoreBackup{0}'},
    'restore ecu status':                       {'id': 'autoRestoreStatusRestoring Site on target: {0}'},

    'configure properties tab':                 {'id': 'autoTabProperties'},
    'configure properties name':                {'id': 'autoPropertiesHeaderName'},
    'configure properties button':              {'id': 'autoPropertiesHeaderButton'},

    'configure floor expander':                 {'id': 'FloorPropertiesExpander'},
    'configure floor plan import':              {'id': 'autoFloorPropertiesImportPlan'},

    'configure components tab':                 {'id': 'autoTabComponentLibrary'},
    'configure components zones':               {'id': 'autoComponentsZones'},
    'configure components luminaires':          {'id': 'autoComponentsLuminaires'},
    'configure components sensors':             {'id': 'autoComponentsSensors'},
    'configure components wallstations':        {'id': 'autoComponentsWallstations'},
    'configure components other devices':       {'id': 'autoComponentsOther Devices'},
    'configure components list':                {'id': 'autoComponentsList'},
    'configure components item':                {'id': 'TextBlock'},

    'map ecu':                                  {'id': 'autoMapEcuIp{0}'},
    'map identify node':                        {'id': 'autoMapIdentifyNode'},
    'map manager details':                      {'id': 'autoMapManagerDetails'},
    'map ecu list':                             {'id': 'autoMapList'},
    'map remove from system':                   {'id': 'autoMapRemoveFromSystem'},
    'map unmap':                                {'id': 'autoUnMap'},

    'networking tool':                          {'id': 'autoNetworkingTool'},
    'refresh list':                             {'id': 'autoRefreshList'},

# New Mapping
    'mapping node':                             {'id': 'autoDeviceNode{0}'},
    'mapping tool':                             {'id': 'autoMappingTool'},
    'mapping network tool':                     {'id': 'autoNetworkTool'},
    'mapping identify node':                    {'id': 'autoNodeIdentify'},
    'mapping continuous identify':              {'id': 'autoNodeContinuous'},
    'mapping node on':                          {'id': 'autoNodeOn'},
    'mapping node off':                         {'id': 'autoNodeOff'},
    'mapping node list':                        {'id': 'autoNodeList'},
    'mapping node template':                    {'id': 'NodeView'},
    'mapping additional actions':               {'id': 'autoNodeAdditionalActions'},
    'mapping node unmap':                       {'id': 'autoNodeUnMap'},
    'mapping node remove from network':         {'id': 'autoNodeRemoveFromNetwork'},
    'mapping node unmapped':                    {'id': 'autoNodeGoToMapped'},

# OLD Mapping
    'mapping tab':                              {'id': 'autoTabMapping'},
    'mapping wink':                             {'id': 'autoWinkECU'},
    'mapping device map':                       {'id': 'autoDoDeviceMapping'},
    'mapping find devices':                     {'id': 'autoScanForDevices'},
    'mapping device list':                      {'id': 'autoMappingDeviceList'},
    'mapping device items':                     {'id': 'GridViewCell'},
    'mapping available device list':            {'id': 'autoMappingAvailableDeviceList'},
    'mapping available device item':            {'id': 'GridViewCell'},
    'mapping bring to site':                    {'id': 'autoBringIntoSite'},
    'mapping additional functions':             {'id': 'autoAdditionalFunctionsCommand'},

    'mapping menu wink':                        {'id': 'autoMenuWinkECU'},
    'mapping menu mapping':                     {'id': 'autoMenuMapping'},
    'mapping menu find devices':                {'id': 'autoMenuScanForDevices'},
    'mapping menu validate mapping':            {'id': 'autoMenuValidateMapping'},
    'mapping menu ecu tools':                   {'id': 'autoMenuECUTools'},
    'mapping menu ecu details':                 {'id': 'autoMenuECUDetails'},
    'mapping menu ecu restart':                 {'id': 'autoMenuECURestart'},
    'mapping menu ecu reboot':                  {'id': 'autoMenuECUReboot'},
    'mapping menu change enc network':          {'id': 'autoMenuChangeEnceliumNetwork'},
    'mapping menu high security level':         {'id': 'autoMenuChangeToHighSecurityLevel'},
    'mapping menu normal security level':       {'id': 'autoMenuRevertToNormalSecurityLevel'},
    'mapping menu search wireless':             {'id': 'autoMenuSearchForWirelessDevices'},
    'mapping menu stop search wireless':        {'id': 'autoMenuStopSearchForWirelessDevices'},
    'mapping menu update firmware':             {'id': 'autoMenuUpdateFirmware'},
    'mapping menu update node firmware':        {'id': 'autoMenuUpdateNodeFirmware'},
    'mapping menu update ch firmware':          {'id': 'autoMenuUpdateChannelFirmware'},
    'mapping menu update ncp firmware':         {'id': 'autoMenuUpdateNCPFirmware'},
    'mapping menu remove from site':            {'id': 'autoMenuRemoveFromSite'},
    'mapping menu options':                     {'id': 'autoMenuOptions'},

    'discovery tool close':                     {'id': 'PART_ButtonClose'},

    'logout':                                   {'navi': ['autoBurgerMenu', 'autoBurgerLog Off']},

# BurgerMenu
    'system information':                       {'navi': ['autoBurgerMenu', 'autoBurgerSystem Information']},
    'backup system':                            {'navi': ['autoBurgerMenu', 'autoBurgerBackup']},
    'restore system':                           {'navi': ['autoBurgerMenu', 'autoBurgerRestore']},
    'user management':                          {'navi': ['autoBurgerMenu', 'autoBurgerUser Management']},
    'manager discovery tool':                   {'navi': ['autoBurgerMenu', 'autoBurgerManager Discovery Tool']},

# Deprecated
    'sync':                                     {'navi': ['autoBurgerMenu', 'autoHeaderHome', 'SynchronizeChanges']},
    'site management':                          {'navi': ['autoBurgerMenu', 'autoBurgerBackup']},
    'take system snapshot':                     {'navi': ['autoBurgerMenu', 'autoHeaderHome', 'Tools', 'TakeSystemSnapshot']},
    'restore system snapshot':                  {'navi': ['autoBurgerMenu', 'autoHeaderHome', 'Tools', 'RestoreSystemSnapshot']},
    'configure':                                {'navi': ['autoConfigure']},
    'configure structure':                      {'navi': ['autoConfigure', 'Structure']},
    'configure mapping':                        {'navi': ['autoConfigure', 'Mapping']},
    'operate':                                  {'navi': ['autoOperate']},
    'analyze':                                  {'navi': ['autoAnalyze']},
}
